'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="BL")>  _
Partial Public Class NHIDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "擴充性方法定義"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Inserttbl_download(instance As tbl_download)
    End Sub
  Partial Private Sub Updatetbl_download(instance As tbl_download)
    End Sub
  Partial Private Sub Deletetbl_download(instance As tbl_download)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.NHIVPN.My.MySettings.Default.BLConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tbl_download() As System.Data.Linq.Table(Of tbl_download)
		Get
			Return Me.GetTable(Of tbl_download)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_download")>  _
Partial Public Class tbl_download
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _f_name As String
	
	Private _f_remark As String
	
	Private _remark As String
	
	Private _SDATE As Date
	
	Private _download As System.Nullable(Of Boolean)
	
	Private _QDATE As System.Nullable(Of Date)
	
    #Region "擴充性方法定義"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Onf_nameChanging(value As String)
    End Sub
    Partial Private Sub Onf_nameChanged()
    End Sub
    Partial Private Sub Onf_remarkChanging(value As String)
    End Sub
    Partial Private Sub Onf_remarkChanged()
    End Sub
    Partial Private Sub OnremarkChanging(value As String)
    End Sub
    Partial Private Sub OnremarkChanged()
    End Sub
    Partial Private Sub OnSDATEChanging(value As Date)
    End Sub
    Partial Private Sub OnSDATEChanged()
    End Sub
    Partial Private Sub OndownloadChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OndownloadChanged()
    End Sub
    Partial Private Sub OnQDATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnQDATEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_f_name", DbType:="NVarChar(100) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property f_name() As String
		Get
			Return Me._f_name
		End Get
		Set
			If (String.Equals(Me._f_name, value) = false) Then
				Me.Onf_nameChanging(value)
				Me.SendPropertyChanging
				Me._f_name = value
				Me.SendPropertyChanged("f_name")
				Me.Onf_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_f_remark", DbType:="NVarChar(200)")>  _
	Public Property f_remark() As String
		Get
			Return Me._f_remark
		End Get
		Set
			If (String.Equals(Me._f_remark, value) = false) Then
				Me.Onf_remarkChanging(value)
				Me.SendPropertyChanging
				Me._f_remark = value
				Me.SendPropertyChanged("f_remark")
				Me.Onf_remarkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_remark", DbType:="NVarChar(200)")>  _
	Public Property remark() As String
		Get
			Return Me._remark
		End Get
		Set
			If (String.Equals(Me._remark, value) = false) Then
				Me.OnremarkChanging(value)
				Me.SendPropertyChanging
				Me._remark = value
				Me.SendPropertyChanged("remark")
				Me.OnremarkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="DateTime NOT NULL", IsPrimaryKey:=true)>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me.OnSDATEChanging(value)
				Me.SendPropertyChanging
				Me._SDATE = value
				Me.SendPropertyChanged("SDATE")
				Me.OnSDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_download", DbType:="Bit")>  _
	Public Property download() As System.Nullable(Of Boolean)
		Get
			Return Me._download
		End Get
		Set
			If (Me._download.Equals(value) = false) Then
				Me.OndownloadChanging(value)
				Me.SendPropertyChanging
				Me._download = value
				Me.SendPropertyChanged("download")
				Me.OndownloadChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QDATE", DbType:="DateTime")>  _
	Public Property QDATE() As System.Nullable(Of Date)
		Get
			Return Me._QDATE
		End Get
		Set
			If (Me._QDATE.Equals(value) = false) Then
				Me.OnQDATEChanging(value)
				Me.SendPropertyChanging
				Me._QDATE = value
				Me.SendPropertyChanged("QDATE")
				Me.OnQDATEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
